services:
  localstack:
    image: localstack/localstack:1.2.0
    ports:
      - "4510-4559:4510-4559"
      - "4566:4566"
    environment:
      SERVICES: "sqs,sns,s3"
      AWS_ACCESS_KEY_ID: "ANY"
      AWS_SECRET_ACCESS_KEY: "ANY_SECRET"
      USE_SINGLE_REGION: "true"
      DEFAULT_REGION: "eu-west-1"
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "./localstack:/etc/localstack/init/ready.d"
